name: Render and Publish Quarto

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: quarto render

      - uses: actions/upload-pages-artifact@v3
        if: github.event_name == 'push'
        with:
          path: .

  deploy:
    if: github.event_name == 'push'
    needs: build

    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/deploy-pages@v4